Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Objectives:
1. Some of the popular languages that Data Scientists use are.
2. Data Science Tools.
3. Some of the commonly used libraries used by Data Scientists include.

Some of the popular languages that Data Scientists use are:
1. R
2. python
3. SQL

Some of the commonly used libraries used by Data Scientists include:
1. Numpy
2. Pandas
3. Matplotlib

Data Science Tools
1. Rstudio
2. Apache Spark
3. tensorflow

Below are a few examples of evaluating arithmetic expressions in Python.

In [1]:
(3*4)+5
#This a simple arithmetic expression to mutiply then add integers

17

In [2]:
200/60
# This will convert 200 minutes to hours by diving by 60

3.3333333333333335

Author:
**Muhammad Yousaf**